#ifndef _CONFIG_H
#define _CONFIG_H

enum Elementos {TOKEN_INVALIDO = -2, FIM_INESPERADO, FIM_ARQUIVO,
				TEMPO, MUSICA, FACA, REPETIR, TOCAR, SE, SENAO, FIM, PAUSAR,
				ABRE_PARENTESES, FECHA_PARENTESES, VIRGULA, PONTO, PONTO_VIRGULA, DOIS_PONTOS, PORCENTO,
				VAR, NOTA, NUMERO, STRING};

enum ArithOp {SOMA, SUBTRACAO, MULTIPLICACAO, DIVISAO};

enum RelOp {IGUAL, IGUAL_IGUAL, DIFERENTE, 	MENOR, MENOR_IGUAL, MAIOR, MAIOR_IGUAL};

#endif