all: 
	g++ -o a.out \
		AnalisadorLexico.cpp \
		AnalisadorSintatico.cpp \
		Nota.cpp \
		Variavel.cpp \
		BlocoComandos.cpp \
		TocarComando.cpp \
		PausarComando.cpp \
		ConstInt.cpp \
		AtribuirComando.cpp \
		ExprIntSimples.cpp \
		ExprIntDupla.cpp \
		SeComando.cpp \
		ExprLogicaDupla.cpp \
		RepetirComando.cpp \
		Playtone.cpp \
		main.cpp